// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7F_cMXsVQwU9jm7LjNr1PpPBaWblBXic',
    appId: '1:196018138114:web:2aa2e4a277ade084490b1b',
    messagingSenderId: '196018138114',
    projectId: 'postly-veil',
    authDomain: 'postly-veil.firebaseapp.com',
    storageBucket: 'postly-veil.firebasestorage.app',
    measurementId: 'G-3202V4SS4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAFOuPYjfKMISA42S1BNGtoyOiHIUC_o',
    appId: '1:196018138114:android:9f60956913c83550490b1b',
    messagingSenderId: '196018138114',
    projectId: 'postly-veil',
    storageBucket: 'postly-veil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABIc-I5zFDEL-zyelJm90rIe5bn-7PXEE',
    appId: '1:196018138114:ios:556cc115e3216448490b1b',
    messagingSenderId: '196018138114',
    projectId: 'postly-veil',
    storageBucket: 'postly-veil.firebasestorage.app',
    iosBundleId: 'com.mottakin.postly.postly',
  );
}
